FROM golang:1.15-alpine as builder

# Where factom-cli sources will live
WORKDIR $GOPATH/src/github.com/FactomProject/factom-cli

# Populate the rest of the source
COPY . .

ARG GOOS=linux

# Build and install factom-cli
RUN ./build.sh

# Now squash everything
FROM alpine:3.12

# Get git
RUN apk add --no-cache ca-certificates curl git

RUN mkdir -p /go/bin

COPY --from=builder /go/bin/factom-cli /go/bin/factom-cli

ENTRYPOINT ["/go/bin/factom-cli"]
